name: Issue Digest

on:
  schedule:
    - cron: '0 0 * * *'  # runs once at 00:00 daily
  workflow_dispatch:

jobs:
  issue-digest:
    runs-on: ubuntu-latest

    steps:
      - name: Run Issue Digest Action
        uses: Eclipse-Dominator/Github_Digest@v0.1.6a-alpha
        with:
          repo: "Eclipse-Dominator/Github_digest_Beta"
          timezone: "Singapore"